// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7oK-J0xYNBQ_xzcJsetf7JuesRgvROKM',
    appId: '1:555327982230:web:4f5e25cd1eb7898961d0b7',
    messagingSenderId: '555327982230',
    projectId: 'charity-3385e',
    authDomain: 'charity-3385e.firebaseapp.com',
    storageBucket: 'charity-3385e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA17IeuxOBHRalXD7apwayyAuXUAQZquOw',
    appId: '1:555327982230:android:a4c9f284eb4aacdd61d0b7',
    messagingSenderId: '555327982230',
    projectId: 'charity-3385e',
    storageBucket: 'charity-3385e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLi7deJJCm4jvL64D8popzn-21c2NE0rc',
    appId: '1:555327982230:ios:f3b8c5bf6580d07f61d0b7',
    messagingSenderId: '555327982230',
    projectId: 'charity-3385e',
    storageBucket: 'charity-3385e.appspot.com',
    iosBundleId: 'com.example.charity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLi7deJJCm4jvL64D8popzn-21c2NE0rc',
    appId: '1:555327982230:ios:0c21baa71d9dcf6161d0b7',
    messagingSenderId: '555327982230',
    projectId: 'charity-3385e',
    storageBucket: 'charity-3385e.appspot.com',
    iosBundleId: 'com.example.charity.RunnerTests',
  );
}
